# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json

options:
  implicit_slide_ends: true
  end_slide_shorthand: true

defaults:
  theme: terminal-dark
